### ISSUE TITLE
The pool cant get any job from the node

### ISSUE THREAD

**Issue by rlinxy** [ufo-project/minepool-backend#3]
Is there any document of how to setup the pool?
config set to 

> "WalletUrl": "127.0.0.1:8181",
  "WalletApiUrl": "http://127.0.0.1:10000/api/wallet",

run the node with 
./ufo-node -p 1621 --peer 202.181.144.43:20015 202.181.144.44:20015 202.181.144.45:20015 mainnet-node02.ufo.link:20015 --stratum_port 8181 --stratum_secrets_path=.api_secret --stratum_use_tls=0

however it stucks at  'login' and no update at all 

> 2020/03/07 21:40:26 cfgPath: /home/ray/minepool-backend/config.json
2020/03/07 21:40:26 infoFile: logs/info.log
2020/03/07 21:40:26 errorFile: logs/error.log
2020/03/07 21:40:26 shareFile: logs/share.log
2020/03/07 21:40:26 blockFile: logs/block.log
[INFO] 2020/03/07 21:40:26.864728 main.go:46: Name:
[INFO] 2020/03/07 21:40:26.864904 main.go:47: Version:
[INFO] 2020/03/07 21:40:26.864917 main.go:48: Build Time:
[INFO] 2020/03/07 21:40:26.864948 main.go:49: Go version:
[INFO] 2020/03/07 21:40:26.864954 main.go:50: Commit id:
[INFO] 2020/03/07 21:40:26.865187 main.go:62: StartDiff: 50 838860800 0.1953125 138034926935811275748695117245540509049022179443407731103250484475985
[INFO] 2020/03/07 21:40:26.865218 main.go:83: Init enonce: 0
[INFO] 2020/03/07 21:40:26.875894 database.go:40: openLevelDB: ./.ufo.lvdb 1  times success.
[INFO] 2020/03/07 21:40:26.877287 database.go:55: OpenMongoDB success
[INFO] 2020/03/07 21:40:26.877743 jobMake.go:127: Connect Agent 127.0.0.1:8181 success
[INFO] 2020/03/07 21:40:26.878007 jobMake.go:32: {"code":0,"description":"Success","id":"login","jsonrpc":"2.0","method":"result"}
[INFO] 2020/03/07 21:40:26.878113 jobMake.go:45: login

**Comment by rlinxy** [comment]
In the config of the pool, it says "WalletUrl", but should it be the url of the node? I don't see any parameter here to run the wallet listening to any specified port.
Please advise, thanks.

**Comment by rlinxy** [comment]
solved, same as beam, have to set miner key and owner key

**Comment by joey-crypto** [comment]
> i got these errors:

D 2020-03-08.00:05:26.100 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[
json.exception.parse_error.101] parse error at 1: syntax error - invalid literal
; last read: 'U'"},"jsonrpc":"2.0"}
I 2020-03-08.00:05:26.109 got Content-Length: 143

when i mine ufo, it shows this error in wallet-api
and in pool ,it shows this error

{"id":"1","jsonrpc":"2.0","method":"mining_authorize","miner":"24c4f4892a61092c24cd803028265b3c9c5021990db931d675cfffd06c8ffed2668.ererer","minertype":"cpu"}
miner.go:148: handleTCPMessage.
miner.go:332: authorizeHandle validAddrress,isvalid: false ,error: Connect wallet-api faild,please check.
miner.go:423: SendMessageToMiner: {"jsonrpc":"2.0","id":"1","code":1,"method":"mining_authorize_result"}
