### ISSUE TITLE
Connect wallet-api faild

### ISSUE THREAD

**Issue by joey-crypto** [ufo-project/minepool-backend#4]
D 2020-03-08.00:05:26.100 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[
json.exception.parse_error.101] parse error at 1: syntax error - invalid literal
; last read: 'U'"},"jsonrpc":"2.0"}
I 2020-03-08.00:05:26.109 got Content-Length: 143

> **when i mine ufo, it shows this error in wallet-api 
> and in pool ,it shows this error**

{"id":"1","jsonrpc":"2.0","method":"mining_authorize","miner":"24c4f4892a61092c24cd803028265b3c9c5021990db931d675cfffd06c8ffed2668.ererer","minertype":"cpu"}
 miner.go:148: handleTCPMessage.
 miner.go:332: authorizeHandle validAddrress,isvalid: false ,error: Connect wallet-api faild,please check.
miner.go:423: SendMessageToMiner: {"jsonrpc":"2.0","id":"1","code":1,"method":"mining_authorize_result"}

**Comment by ufo-project** [comment]
you need to execute a binary file called wallet-api

e.g.
```
./wallet-api --node_addr=127.0.0.1:1621 --pass=123456 --use_http=1 --ip_whitelist=127.0.0.1
```
