### ISSUE TITLE
the submit block will report to which miner address? the pool wallet itself?  

### ISSUE THREAD

**Issue by davidufochain** [ufo-project/minepool-backend#5]
and the option "--treasury=treasury.bin" is display invalid, why?
I do not found the balance on my pool wallet/miner wallet, please comment that, thanks

**Comment by ufo-project** [comment]
1. The option "--treasury=treasury.bin" is necessary right now for ufo-node
2. Use ufo-wallet to create mnemonic words,, at the same time you can get wallet.db also, then you need to export secret subkey1 and owner key
3. Start ufo-node using secret subkey1 and owner key to make sure the mining reward to the right mining address
4. Make sure wallet-api and wallet.db are in the same directory, and then start wallet-api
5. Request wallet-api and you can get what you want

plz check it
https://github.com/ufo-project/minepool-backend/blob/master/README.md
